# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fccbb08b390856c15c08c2b5254e271013e4db3fc2d6905abc1fabbed28e60158427d6c6208a4f9361401e751468289610d05dcfa915eeabc6a4b01b0604c588

test:
  secret_key_base: 0521a828fb32698eaea3b125772fb4a236c51f9bc31881955d7d69ffa5b6603e4c6a153dabf608784bcde40c26e85769b39164125c64df46bf0eab70370fde7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
